### PR TITLE
Anam final edit

### PR DESCRIPTION
**Pull request by Anam-Mahmood**

### CODE REVIEW

**Comment by Anam-Mahmood** [comment]
@samayamadhavan Can you check the changes now :)

**Comment by Anam-Mahmood** [comment]
@samayamadhavan Please check the changes made to the code pattern

**Review by samayamadhavan — CHANGES_REQUESTED** [review]
Anam, I do see the gifs and images are being referenced from your personal GitHub space. might be a better idea to  change them to this same repo or however the originals were.

**Comment by Anam-Mahmood** [comment]
@samayamadhavan I have fixed the issue, please review now.

**Review by samayamadhavan — APPROVED** [review]

**Comment by samayamadhavan** [comment]
LGTM! thank you for making these changes, @Anam-Mahmood 

FYI - @horeaporutiu

**Comment by horeaporutiu** [comment]
@samayamadhavan what is this PR for?

**Comment by samayamadhavan** [comment]
@horeaporutiu -  updates to Watson Studio/WML screenshots/gifs

@Anam-Mahmood - please add any specifics if you'd like.

**Comment by Anam-Mahmood** [comment]
Yeah, this is the updated version of AutoAI, with gifs to the new deployment method :)

**Pull request merged**
